{% set name = "linux-perf" %}
{% set version = "6.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://cdn.kernel.org/pub/linux/kernel/v{{ version.split(".")[0] }}.x/linux-{{ version }}.tar.xz
  sha256: 2fcc07e1c90ea4ce148f50f9beeb0dca0b6e4b379a768de8abc7a4a26f252534

build:
  number: 1
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - sysroot_linux-64 2.17  # [linux64]
    - make
    - flex
    - bison
  host:
    - elfutils
    - binutils
    - libcap
    - libnuma
    - libunwind
    - libzlib
    - openssl
    - xz
    - zlib
    - zstd
    - python
    - setuptools
  run:
    - python

test:
  commands:
    - perf list

about:
  home: https://www.kernel.org
  summary: Performance analysis tools for Linux
  description: |
    Performance counters for Linux are a new kernel-based subsystem that
    provide a framework for all things performance analysis. It covers hardware
    level (CPU/PMU, Performance Monitoring Unit) features and software features
    (software counters, tracepoints) as well.
  license: GPL-2.0-only
  license_file: LICENSES/preferred/GPL-2.0
  doc_url: https://docs.kernel.org/

extra:
  recipe-maintainers:
    - chrisburr
